"""Initial schema setup

Revision ID: 97f2d2741fd8
Revises: 3675322e5772
Create Date: 2026-06-16 20:17:30.072888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97f2d2741fd8'
down_revision: Union[str, None] = '3675322e5772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('receipt_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales', 'bill_receipts', ['receipt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'receipt_id')
    # ### end Alembic commands ###
