"""Initial schema setup

Revision ID: be9828fe59c6
Revises: 97f2d2741fd8
Create Date: 2026-06-17 07:52:01.725693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be9828fe59c6'
down_revision: Union[str, None] = '97f2d2741fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'bill_receipts', 
        'status',
        existing_type=sa.Enum('PENDING', 'PAID', 'CANCELLED', name='receiptstatus'),
        type_=sa.String(length=50),  # FIXED: Use native SQLAlchemy String
        existing_nullable=False,
        postgresql_using='status::text' # FIXED: Explicitly cast existing ENUM values to plain text strings
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'bill_receipts', 
        'status',
        existing_type=sa.String(length=50),
        type_=sa.Enum('PENDING', 'PAID', 'CANCELLED', name='receiptstatus'),
        existing_nullable=False,
        postgresql_using='status::receiptstatus' # Reverts strings safely back to the database enum type
    )
    # ### end Alembic commands ###
