# app/repositories/sales_repo.py
from app.models.schema import Sale, BillReceipt, Product, Customer, Payment
from datetime import datetime
import random

PAGE_SIZE = 30


class SalesRepository:
    def __init__(self, db_session):
        self.db_session = db_session

    def generate_unique_receipt_number(self) -> str:
        """Generates a distinct token tracking string pattern."""
        timestamp = datetime.utcnow().strftime("%Y%m%d%H%M")
        rand_suffix = random.randint(1000, 9999)
        return f"REC-{timestamp}-{rand_suffix}"

    # ------------------------------------------------------------------
    # Receipts
    # ------------------------------------------------------------------

    def get_all_receipts(self, search_query: str = None, page: int = 1):
        """Returns (records, total_count) ordered newest-first, paginated."""
        query = self.db_session.query(BillReceipt)
        if search_query and search_query.strip():
            wq = f"%{search_query.strip()}%"
            query = query.outerjoin(Customer).filter(
                (BillReceipt.receipt_number.ilike(wq)) | (Customer.name.ilike(wq))
            )
        query = query.order_by(BillReceipt.receipt_date.desc())
        total = query.count()
        records = query.offset((page - 1) * PAGE_SIZE).limit(PAGE_SIZE).all()
        return records, total

    def get_receipt_by_id(self, receipt_id: int) -> BillReceipt:
        return self.db_session.query(BillReceipt).filter(BillReceipt.id == receipt_id).first()

    # ------------------------------------------------------------------
    # Sales
    # ------------------------------------------------------------------

    def get_all_sales_standalone(self, search_query: str = None, page: int = 1):
        """Fetches flat transactional logs filtered by product attributes, paginated."""
        query = self.db_session.query(Sale).join(Product)
        if search_query and search_query.strip():
            query = query.filter(Product.name.ilike(f"%{search_query.strip()}%"))
        query = query.order_by(Sale.sale_date.desc())
        total = query.count()
        records = query.offset((page - 1) * PAGE_SIZE).limit(PAGE_SIZE).all()
        return records, total

    # ------------------------------------------------------------------
    # Payments
    # ------------------------------------------------------------------

    def get_all_payments(self, page: int = 1):
        """Returns (records, total_count) for the payments ledger, newest-first."""
        query = self.db_session.query(Payment).order_by(Payment.payment_date.desc())
        total = query.count()
        records = query.offset((page - 1) * PAGE_SIZE).limit(PAGE_SIZE).all()
        return records, total

    # ------------------------------------------------------------------
    # Receipt creation
    # ------------------------------------------------------------------

    def create_receipt_with_sales(self, receipt: BillReceipt, items_list: list) -> BillReceipt:
        """Atomically inserts parent receipt metadata alongside dependent sub-sales rows."""
        self.db_session.add(receipt)
        self.db_session.flush()  # Secure valid autogenerated receipt ID before binding children
        for sale_item in items_list:
            sale_item.receipt_id = receipt.id
            self.db_session.add(sale_item)

            # Deduct quantities directly from available stock profiles
            product = self.db_session.query(Product).filter(Product.id == sale_item.product_id).first()
            if product:
                if product.quantity < sale_item.quantity:
                    raise ValueError(
                        f"Insufficient Stock: {product.name} only has {product.quantity} remaining items."
                    )
                product.quantity -= sale_item.quantity
                self.db_session.add(product)
        self.db_session.commit()
        return receipt