# app/repositories/sales_repo.py
from app.models.schema import Sale, BillReceipt, Product, Customer
from datetime import datetime
import random

class SalesRepository:
    def __init__(self, db_session):
        self.db_session = db_session

    def generate_unique_receipt_number(self) -> str:
        """Generates a distinct token tracking string pattern."""
        timestamp = datetime.utcnow().strftime("%Y%m%d%H%M")
        rand_suffix = random.randint(1000, 9999)
        return f"REC-{timestamp}-{rand_suffix}"

    def get_all_receipts(self, search_query: str = None):
        query = self.db_session.query(BillReceipt)
        if search_query and search_query.strip():
            wq = f"%{search_query.strip()}%"
            query = query.outerjoin(Customer).filter(
                (BillReceipt.receipt_number.ilike(wq)) | (Customer.name.ilike(wq))
            )
        return query.order_by(BillReceipt.receipt_date.desc()).all()

    def get_receipt_by_id(self, receipt_id: int) -> BillReceipt:
        return self.db_session.query(BillReceipt).filter(BillReceipt.id == receipt_id).first()

    def get_all_sales_standalone(self, search_query: str = None):
        """Fetches flat transactional logs filtered by product attributes."""
        query = self.db_session.query(Sale).join(Product)
        if search_query and search_query.strip():
            query = query.filter(Product.name.ilike(f"%{search_query.strip()}%"))
        return query.order_by(Sale.sale_date.desc()).all()

    def create_receipt_with_sales(self, receipt: BillReceipt, items_list: list) -> BillReceipt:
        """Atomically inserts parent receipt metadata alongside dependent sub-sales rows."""
        self.db_session.add(receipt)
        self.db_session.flush() # Secure valid autogenerated receipt ID before binding children

        for sale_item in items_list:
            sale_item.receipt_id = receipt.id
            self.db_session.add(sale_item)
            
            # Deduct quantities directly from available stock profiles
            product = self.db_session.query(Product).filter(Product.id == sale_item.product_id).first()
            if product:
                if product.quantity < sale_item.quantity:
                    raise ValueError(f"Insufficient Stock: {product.name} only has {product.quantity} remaining items.")
                product.quantity -= sale_item.quantity
                self.db_session.add(product)

        self.db_session.commit()
        return receipt